### ISSUE TITLE
How do I use Rust bytes as OCaml bytes ?

### ISSUE THREAD

**Issue by yoshihiro503** [zshipko/ocaml-rs#45]
I want to call a function that returns values of `Vec<u8>` from OCaml, but it will be an `int array` in OCaml.
What do I have to do to get a value of type bytes or string in OCaml?

**Comment by tizoc** [comment]
Hi @yoshihiro503, at the moment I think the only way around that is to make it so that the Rust function returns either a `String` or `&str` (which you should be able to do without having to clone the `Vec<u8>` bytes), see this table: https://github.com/zshipko/ocaml-rs#type-conversion

What you want to do will be possible in future versions once the integration between `ocaml-*` and `ocaml-interop` has been completed, because in that case the mapping between types will not be a fixed 1-to-1 relation anymore.

**Comment by zshipko** [comment]
I think there are two ways of doing this right now:

1. It's not mentioned in the README type chart, but if you return a `&[u8]` value that will be converted to OCaml bytes
2. You could allocate the bytes in OCaml and access the borrowed data from Rust, something like this:
```rust
let a = Value::alloc(strlen, Tag::STRING);
let data: &mut [u8] = a.clone().into(); 
```

As @tizoc mentioned, there is also work being done to improve the API around type conversions.
