### ISSUE TITLE
Missing ChangeLog and releases

### ISSUE THREAD

**Issue by lefessan** [zshipko/ocaml-rs#51]
I wrote a binding using v0.19.0, but it does not compile with v0.20.0 . The lack of ChangeLog between the 2 versions makes it a bit difficult to understand the source of the incompatibility.

**Comment by tizoc** [comment]
Hello @lefessan, if you use `ocaml-derive`, my guess is that the incompatibility is probably related to the integration with [ocaml-interop](https://github.com/simplestaking/ocaml-interop).

There is another big change coming to `ocaml-interop` that will probably affect `ocaml-derive` too, so my advice would be to stay with `0.19.*` for a bit (but let's see what @zshipko thinks).

I know it is inconvenient but the result will be a version that is still very convenient to use, but safer.

**Comment by lefessan** [comment]
My projcet issue was with the renaming from `ToValue` to `IntoValue`. 
But this issue is more about the fact that the lack of ChangeLog (and release tags in git) will make it harder for developers to keep up with such small incompatibilities over time.

**Comment by zshipko** [comment]
Sorry about that, `0.20` is kind of an intermediate release before integrating `ocaml-interop` more directly. Like @tizoc suggested, staying on `0.19` is not a bad option, since there will probably be a lot more changes coming. 

Here are the updates from the latest release:
- `Value` methods marked as `unsafe` since the `Value` API is now considered the "unsafe" API - `ocaml-interop` is the safer choice
- `ToValue` renamed to `IntoValue`
- All functions that may allocate take a reference to `ocaml::Runtime` (there is an implicit `gc` variable provided when using `ocaml-derive`)

I will add this list to a CHANGES file right now so it is clear for others in the same position. I can also remember to tag releases  moving forward, thanks for the suggestion.

**Comment by lefessan** [comment]
I think the best would already be to keep the README.md examples and the ocaml-rust-starter project up-to-date with the changes. I started using the Rust binding by following these examples, so I assume that most people do the same. `ToValue` is still the syntax presented in the README.md file.

**Comment by zshipko** [comment]
That makes sense, `ocaml-rust-starter` should be fine, but I updated the ocaml-rs README to match 0.20 - I wish there was a better way to verify that code compiles correctly at release time. I think I will probably end up moving all of the examples into a dedicated `examples/` folder before the next release.
