### ISSUE TITLE
Failure when building ocaml-sys docs on docs.rs

### ISSUE THREAD

**Issue by tizoc** [zshipko/ocaml-rs#54]
See: https://docs.rs/crate/ocaml-sys/0.20.0

Something changed in 0.20 that broke the build script when some of the env variables are not set (I noticed this elsewhere before seeing this in docs.rs).

I'm fixing something else now, but will let you know if I figure out what is wrong.

**Comment by zshipko** [comment]
I made this change: https://github.com/zshipko/ocaml-rs/commit/cac6a2c2153bdcedfee6afe093ff583cde8f4dc7#diff-2620be2afc249413fa14ee1f678c9c7ab8f0658f44f5c6d49cff57956c716debL143 because of an issue I was having where `build.rs` was silently failing on my machine. I will also look into this more - I'm hoping to have some time to make a few ocaml-rs updates in the next week or two.

**Comment by tizoc** [comment]
@zshipko ohhh now that I look at that, is is just a matter of changing `docs-rs` there to `without-ocamlopt`, right?

**Comment by zshipko** [comment]
Good catch, that seems like it should do it. I will make a 0.20.1 release for ocaml-sys right now.

**Comment by zshipko** [comment]
That fixed it: https://docs.rs/ocaml-sys/0.20.1/ocaml_sys/
