### ISSUE TITLE
undefined symbols _caml_local_roots

### ISSUE THREAD

**Issue by mimoo** [zshipko/ocaml-rs#72]
Hey!

Any idea what could cause this error? Sorry, I'm grasping at straws here :(

```
Undefined symbols for architecture x86_64:
  "_caml_local_roots", referenced from:
      ocaml_sys::state::local_roots::h5f371de5d79ec31b in libmarlin_plonk_stubs.a(ocaml_sys-0ebbd1c370daa908.ocaml_sys.1za79sff-cgu.8.rcgu.o)
      ocaml_sys::state::set_local_roots::hc721dba7b42375f7 in libmarlin_plonk_stubs.a(ocaml_sys-0ebbd1c370daa908.ocaml_sys.1za79sff-cgu.8.rcgu.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
```

**Comment by tizoc** [comment]
@mimoo Hi! are you compiling with the right OCaml version? it looks like you are compiling code with two different versions. There were some API changes between 4.09 and 4.10, and that symbol you are missing there is related to that.

**Comment by mimoo** [comment]
what do you mean "right ocaml version"?

**Comment by tizoc** [comment]
@mimoo things need to be compiled differently depending on the OCaml version detected, see: https://github.com/zshipko/ocaml-rs/blob/master/sys/build.rs#L129-L133

The error you pasted tells me that during compilation an OCaml version different to the one to which the code is being linked against later. If you are using opam and have many switches you have to make sure that the correct version is being detected, otherwise there will be a mismatch between what was compiled and what is being linked.

**Comment by tizoc** [comment]
@mimoo as a quick (but not ideal) workaround, you can specify the `caml-state` feature, that is going to force the library to assume that you are compiling against OCaml >= 4.10.

**Comment by mimoo** [comment]
Oh! I see, indeed it was because of this :) thanks a lot! (I guess dune isn't aware of an OCaml version change, I had to delete `_build`). Thanks again!
