### ISSUE TITLE
when to call finalize?

### ISSUE THREAD

**Issue by mimoo** [zshipko/ocaml-rs#73]
Hey!

When it comes to custom types, there are two examples given. One in the README:

```
unsafe extern "C" fn mytype_finalizer(v: ocaml::Raw) {
    let ptr = v.as_pointer::<MyType>();
    ptr.drop_in_place()
}

ocaml::custom_finalize!(MyType, mytype_finalizer);
```

and one in the docs: https://github.com/zshipko/ocaml-rs/blob/ff07e873ed502eb25b8429a99c86cc831e4a7d1f/src/custom.rs#L190 which doesn't do anything for the finalizer. It is not clear to me if we have to drop the value or not in the finalizer.

In general it is not clear to me exactly when Rust is not in charge of freeing memory anymore.

**Comment by zshipko** [comment]
You don't always need to call `drop_in_place`, the current implementation of custom values embeds the Rust type in a custom block, this transfers the ownership of memory from Rust into OCaml and will be cleaned up by the GC. A custom value is the same thing as any other OCaml value, it just allows you to store/access a Rust value stored inside. 

The case where you would want to call `drop_in_place` (or equivalent) is when your type has a specific behavior when dropped, this won't be automatically triggered otherwise. So if there is a `Drop` implementation that frees some resources or performs some kind of cleanup you would need to include that in finalize somehow.

**Comment by mimoo** [comment]
Thanks for the answer! So, is it really necessary here: https://github.com/zshipko/ocaml-rs/blob/ff07e873ed502eb25b8429a99c86cc831e4a7d1f/test/src/custom.rs#L21

and here: https://github.com/zshipko/ocaml-rs/blob/ff07e873ed502eb25b8429a99c86cc831e4a7d1f/src/custom.rs#L201

**Comment by mimoo** [comment]
Now I'm getting even more confused :) I wrote this as a proof of concept and it looks like I do have to call `drop_in_place` otherwise it never gets garbage collected: https://github.com/mimoo/trying_to_understand_ocaml_rs

**Comment by zshipko** [comment]
Yeah, your edit is correct. Since `Rc` implements `Drop` you should be calling `drop_in_place` - I will make this connection more explicit in the documentation and maybe there is a way to improve the macro to handle this better.

**Comment by mimoo** [comment]
My understanding is that it's never unsafe to drop_in_place, and that it's probably a no-op when it doesn't matter, so why not just do it automatically?

**Comment by zshipko** [comment]
That's what I'm thinking, however I think it would only work when using the `custom!` macro since the type needs to be known in that finalizer function

**Comment by zshipko** [comment]
`Custom` now defaults to calling `drop_in_place` if no finalizer is set
