### ISSUE TITLE
A potential way to automatically generate the corresponding .ml files?

### ISSUE THREAD

**Issue by mimoo** [zshipko/ocaml-rs#76]
Hey!

Sorry for using the issues to ask questions, but I wasn't sure what else to use ^^ And thanks for the answer to my other questions.
I found that writing the FFI code in OCaml was very error prone, and also it felt unnecessary, as it was redundant with what I wrote in Rust. For example, for C FFI in Rust you can automagically generate the bindings via https://github.com/rust-lang/rust-bindgen

I was wondering if there could be a way to automatically generate the corresponding *.ml files from Rust as well here. Food for thought, but maybe you have an opinion here?

**Comment by tizoc** [comment]
> I was wondering if there could be a way to automatically generate the corresponding *.ml files from Rust as well here. Food for thought, but maybe you have an opinion here?

We discussed this in the past. It would be a great improvement, because as you correctly point out, that part is error-prone (it is the main pain-point I have when writing FFI code, everything else works very well). If your definitions don't match on both languages, nothing will warn you, all you will get is a segfault at runtime.

With generated glue code both language's type-checkers would be able to validate that the mappings are correct.

But thinking about how to implement that feature properly and doing the work would require some time, and I don't have time to spare right now. I think @zshipko's situation is the same.

**Comment by mimoo** [comment]
I have some code here that works for us: https://github.com/o1-labs/proof-systems/pull/156 I can work on integrating this on ocaml-rs

**Comment by tizoc** [comment]
@mimoo that is great, I really like the approach.

**Comment by tizoc** [comment]
@mimoo once I have some free time I will play with that and see if I can adapt it to ocaml-interop, but eventually it would be very cool if a single library that can work with both ocaml-rs and ocaml-interop can be produced (maybe one generic crate for the common parts, and then two other crates that use it, one for ocaml-rs and another for ocaml-interop)

**Comment by zshipko** [comment]
`ocaml-derive` now includes the `ocaml::sig` macro which can be used with `ocaml-build` to generate ml/mli files: https://github.com/zshipko/ocaml-rs/blob/master/build/README.md

**Comment by mimoo** [comment]
Interesting, I'm wondering what the differences are with ocaml-gen now :o

**Comment by zshipko** [comment]
It looks like `ocaml-gen` is still a bit more automatic since `ocaml::sig` requires you to manually write the OCaml signature
