### ISSUE TITLE
More documentation on advantages of writing extensions in Rust over C

### ISSUE THREAD

**Issue by aryx** [zshipko/ocaml-rs#80]
Could you explain in the README or blog post or somewhere the advantages of ocaml-rs over
writing the extensions in C. For example I could see a simple toy example where
it's very easy to make a mistake in the C extension, which leads to a segfault, but
when you port the C extension to Rust, then the Rust borrow checker finds statically
the bug you would have in the C code.

Love OCaml, love Rust, just want more doc, so I would have a bigger incentive
to port some C extensions I know of in Rust.

**Comment by crackcomm** [comment]
It certainly has it advantages but there are also disadvantages, there is C compiler included in every linux distro but you have to install rust separately. C has builtin support in dune whereas when you change Rust code it often fails to recompile the source. Using dune with esy I often have to remove both `*.so`, `*.a` files and `*.rs` files copied to build directory, not sure if the same happens when not using esy but it's been a pain for me and I have to use esy to overwrite certain packages. If you have working code in C and you want to port it to Rust I highly discourage you from doing that. On the other hand if you have already existing code in Rust and want to provide OCaml bindings for it you shouldn't need more reasons.

**Comment by aryx** [comment]
thx!
